CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "accounts_useraccount_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "useraccount_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "accounts_useraccount_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "useraccount_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "accounts_useraccount_groups_useraccount_id_group_id_9e1772b3_uniq" ON "accounts_useraccount_groups" ("useraccount_id", "group_id");
CREATE INDEX "accounts_useraccount_groups_useraccount_id_1eefb17f" ON "accounts_useraccount_groups" ("useraccount_id");
CREATE INDEX "accounts_useraccount_groups_group_id_07495d90" ON "accounts_useraccount_groups" ("group_id");
CREATE UNIQUE INDEX "accounts_useraccount_user_permissions_useraccount_id_permission_id_54014a73_uniq" ON "accounts_useraccount_user_permissions" ("useraccount_id", "permission_id");
CREATE INDEX "accounts_useraccount_user_permissions_useraccount_id_9ee22c82" ON "accounts_useraccount_user_permissions" ("useraccount_id");
CREATE INDEX "accounts_useraccount_user_permissions_permission_id_5751e5ed" ON "accounts_useraccount_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0));
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "team_team" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "status" varchar(10) NOT NULL, "created_by_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "team_team_members" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "team_id" bigint NOT NULL REFERENCES "team_team" ("id") DEFERRABLE INITIALLY DEFERRED, "useraccount_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "team_team_created_by_id_368dcdf9" ON "team_team" ("created_by_id");
CREATE UNIQUE INDEX "team_team_members_team_id_useraccount_id_f9985db5_uniq" ON "team_team_members" ("team_id", "useraccount_id");
CREATE INDEX "team_team_members_team_id_5e29636e" ON "team_team_members" ("team_id");
CREATE INDEX "team_team_members_useraccount_id_f7b58a2a" ON "team_team_members" ("useraccount_id");
CREATE TABLE IF NOT EXISTS "accounts_useraccount" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "email" varchar(255) NOT NULL UNIQUE, "first_name" varchar(255) NOT NULL, "last_name" varchar(255) NOT NULL, "is_active" bool NOT NULL, "is_staff" bool NOT NULL, "active_team_id" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "team_invitation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "email" varchar(254) NOT NULL, "status" varchar(20) NOT NULL, "date_sent" datetime NOT NULL, "team_id" bigint NOT NULL REFERENCES "team_team" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "team_invitation_team_id_a4c7c930" ON "team_invitation" ("team_id");
CREATE TABLE IF NOT EXISTS "project_project" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "created_by_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED, "team_id" bigint NOT NULL REFERENCES "team_team" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "project_project_created_by_id_b4ef8dd6" ON "project_project" ("created_by_id");
CREATE INDEX "project_project_team_id_eb461f4a" ON "project_project" ("team_id");
CREATE TABLE IF NOT EXISTS "project_entry" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "minutes" integer NOT NULL, "is_tracked" bool NOT NULL, "created_at" datetime NOT NULL, "created_by_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED, "project_id" bigint NULL REFERENCES "project_project" ("id") DEFERRABLE INITIALLY DEFERRED, "team_id" bigint NOT NULL REFERENCES "team_team" ("id") DEFERRABLE INITIALLY DEFERRED, "status" varchar(20) NOT NULL);
CREATE INDEX "project_entry_created_by_id_5e1c2f5c" ON "project_entry" ("created_by_id");
CREATE INDEX "project_entry_project_id_5cb610ba" ON "project_entry" ("project_id");
CREATE INDEX "project_entry_team_id_4c010d9c" ON "project_entry" ("team_id");
CREATE TABLE IF NOT EXISTS "team_absence" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "start_at" date NOT NULL, "end_at" date NOT NULL, "status" varchar(10) NOT NULL, "team_id" bigint NOT NULL REFERENCES "team_team" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_useraccount" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "correct_date" CHECK ("start_at" <= ("end_at")));
CREATE INDEX "team_absence_team_id_1876b698" ON "team_absence" ("team_id");
CREATE INDEX "team_absence_user_id_2a6f79f3" ON "team_absence" ("user_id");
